language: R
sudo: false
cache: packages
warnings_are_errors: false

r_packages:
  - covr

after_success:
  - Rscript -e "covr::codecov()"

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
  - secure: Pjchnb7BDRh0M5O62aXudglDqBfq5LFP0CNnh0Z1w0fb7vzdXhdiK0/QMEGXSjfhOLvxslj47t4S6PmEiNQbRWxwn1gUBzw+TNnw9ouaeaWjDE9lfvIOudz4t6EwZNEaIpz7u+cdCQ2UOo6+1s50q32I0c+sJJGZkVQ03qoeTidat59CHNB7HgFQxpN3MhmkRZF72JroXlebEwjrGGQsa737sDNpS8j8Iwo+kMnsqnI7C/szDa/kKKt7Vybdu0YEJ4c5Ft3TwrrQ7IH8gmnwlXI6yzgB+a2W0FBIg6QcDozptGXUskebvMAaz02wvKbCil1emWaxamN6A5nrdYLM29IMJmwG6ZHwTpOropSNQNP/MHRLP/8lVAfkIigrSRz0N9Oo+rd2DWIcqQHIVhpqa2Vp5if5XKEIr+VITfizsOilMVXs0Fh7uzD8TWqZ0Lr5oirZIfR0uxlOjHH8GUsvq9v2bfKzmoPimAIGX+KB5ZPM7tmY8d7UW1jtD6vG9Q/C61hgDdLwSJ9W4rz5nidXrG2v8okcxMDnghoFA+r0H4QGWrH7QcOOY0uYKKPRCcKY2yuZ2ZBQm/+bNc2jMfwJNaxkQw5wJZaE3BIMaqyZ2+RKtsinx85I9A3e6FNaujfgXkko3qA+SYTrWq2RfGDtQkPcyCrECWbBxDV/FD+Vku8=
  - secure: bJVTwJgqTG238ASJ2RQetvUfZYguBFAFq/F8GW6uMqMBP6b73khhFNmDliD69J9r8+qvnAgDD/hHdrP3zmaAm1hbciDUTVy4kbPIfXYvpcH1Lv3p/GeAsG8iOkLr8ZqH7LNIzBtVG+wW5xKgpVHmoHq23gi+SpDtV5+uAa+5I4BW3Zv0UCXQ4JesuSYhj+qwiVt7dFbK8e6EWuqUIqwu3pP1Z38+uHe1A+J+4B0ixPg7gwCoug7ftykFmU0T/NOtyqEoMPkDxByxkk203eocnbWIYsbHxNM+VssoK84HSBqKXfbdroFrDt7h+uspNVrDzZ6tbazDwB10i09YNMQN917Ch+LFYGP89yXIXByYiwjW8diIptdI3tU17KFCpzL4zqFwpt/UA68JeF8vrEr2721hgLSu26OV+TFU/kuGRyntlsKGUBjmjPxEwH+fW/A9MNoYS7boHgFSIWcGJjZej96rSfOoaZfX+dGt5dUciBT11I1+i0xXojIJJxWFbyuAzCyiphTC04souAY0uYbzrSNSYAHY0uWbG1Wg6ammR4n9+0wKi8Q/mpEKw7Zmfit+TUxJjbu4QURIDwItEpV0irZSIbg5BPwXUB24pT/GNpqOysABBFL8p2xvvJAdDvJ99UaPqYqg8JRrs34G/a4lDdV3urY/4Ljy8qmwf1/wncs=
