language: r
r:
- release
- oldrel
dist: bionic
sudo: false
cache: packages
warnings_are_errors: false
branches:
  only:
  - master
  - dev
latex: false
addons:
  apt:
    packages:
    - libmagick++-dev
    - libharfbuzz-dev
    - libfribidi-dev
r_packages:
- pkgdown
- hexSticker
- covr
- here
after_success:
- Rscript -e 'library(covr); codecov()'
notifications:
  email:
    recipients:
    - andrew@exegetic.biz
    on_success: change
    on_failure: change
before_deploy:
- Rscript inst/hex/emayili-hex.R
- Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  github_token: "$GITHUB_TOKEN"
  skip_cleanup: true
  on:
    branch: master
  local_dir: docs
  target_branch: gh-pages

# How to add environment variables: https://docs.travis-ci.com/user/environment-variables/.
env:
  global:
  - secure: bB6tfEIerhu19sPKNfarF80VuTQ0vsesSFSEcrgIwW3h/u7tkCVFc0kTtnTw3zgt0bo6zIFDvwxXiEcztxMKttwAuOQivmO6t4Oh773QDI6upeKliFZtlVVAA8E3OJt+zWrbw3dCnmuLfdPKMic9EdSP63a1R6Z9deoHs5tmNFUQLTL2Mejp+dE0UTwBj7T1CIbIt0bFXnD4eJUlXTsOnNnGuOSFiUb9Fc/Enap3v7HSMZPyimwK2O6s/wIBXbSnNwrlSwaXKiEBSJ0eLriWJgGuP1C3BhLxUfkIAZmcld/DeXmGZlXgLR5jqok49jJ/wyiTiEPljXxxlWl7Ph7c104OwLLW+k2dNHbryrRSKd0xfdRoEKFAHlvQA2ORT9/C2sLGLbJclAwe68FdS+4LWGm7wVknQr7Djp56BSRfGFYPZs6veGaXF5xg54+koKOdbAK2Modk3RmbFHGrsbp538smmVgx3QtU7RvIBXBKWCiQvINFmA6a0r3ll5BKX4m+TcBGWlJDK9U1onteej7cJzb1pk9yw07gtBW30LDzhRl8VrZ8ggRCf37+SY74AkJZRmwGh5FcH2yZZ+PFqmTixIoqB8K4E2AgWoZetZq+Ja/lih8xM1GlJ34p3KqCOyA7jpHAgXQnpkyUCVLObuCm2H/Pyr5BSqyEvvtXsXs/S4o=
  - secure: QmPZjwRg7pDdxUwSS92DmUIrjG7YhIiQKZWbtXBRRuZ7OyZB+rJvgNeuehrjhaF0za2Se0RRkTC5YAwq98kKtM+T6fC33qxz8Bwxk9mGnXJIyhOWyPlBKe6R1c4v3vChd04d6tE0jTioz56/k4EtPHyiNMgeqbqW0ewqSV4Oia8AphWxWospdRZtFH3Np+hkg+tyFBsPZcAhsnNb5nf6cmxlJHuHRf315XLRr04F4zrE3jRaIAdkGJEmOwo0YDtDkTAQCjA5BqLpnqCTCxw+Dh2mJOtTH6yHnehjuZtFGSY7MoyEMXZx/9r83rZtOx8vW+9V6cZJmjCKDvNMtAn0nQ4vrKSK5VvPZxTaJp2TxrpG3weIxQXh/we9lY4gTefIlHo0X4IA1xRCXQJNj4Icx8XmVwHIzxmqWIBIM6OfcA9ty5AEi0G7qT81JlTYF0bberMEdNaZxTeCsIcip7+ozTBXMyfnP7GrzlYfA4mMb/EY2VRh1lQMQW3awcJzFiScB0Zg5/yDeNyyIVPqTTpF69XwiE8wc9z7OTtmwa0qSJFJ66tNPxcqiW8ecmmzMIE/YMp20nKBKhhcdQp3qBMGhfT36yBpQBWVZx99h3K4TsbSRAD32LXcNHpl0rIeGqR5nGLmFKxKjr0K6O4Do+PPcaJrhY5uJGN5d7icQkrxpTU=
  - secure: hC8ZJm77zy3XAs12nlipwRWc/39GPeXzIpdFchjnXTT048Q1ZOr2DSvmFWaCyFf45bcv4NI6rOViTdMZwb6ya3DwLn0DjspMqZjxQenbvwGsRL74Fb0Y+3nlnVK2oNcIQFcHcmk3r13vTen39Tu6z9RHmZwioE0udz1WsdnD+2A7o9JKll2tuZ3/B2yOJw6A418hQ2coaakWkxTBpzGvfYMDrlraRSPDyhaaRCBG/X7C4gZRzlURb2lUcGeF5Xv62oLiXXI0WbyuxyHJdfPawZ7K2Q64kQvhoqA1pxdnPlFHc3q+oUc7FUKFSu+9uYE1w9Ipq5wZTncpIxY+GPeQQukXiM/2G7RZeLim+aOQNp3rsAmPJdXvf/stiTCV+FGli3s6hMmBh2Z4B7t2IK+e3SCB5lKBa3Sdewh3PTd22apEhXEDrOhkQy4iCbHNzvN8naWhjukQwooeOgVtu+qXvUNitMxyJJr8l2fBRz1AtXEwdmiiem6qStnYUf91ykfTNo5dFwAUgo9vEAFlK2XcoP2iCmjWUajbv7pFdaBnZkBi/wn4/MumRI/Linsv0DrRi6FLAPkPdNIVaR9w5h0DOXRe08XlNB1IgKjCi1X5EiWMZomoNBpw9/vUCu514DR2UsW82QXO6KON3skgqHn4e6bOnTNnxoasXQ07KCASLk8=
